name: hagglex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: 0.22.0
  graphql_flutter: ^3.0.1
  material_design_icons_flutter: ^4.0.5955
  shared_preferences: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/



